export const CREATE_TODO = 'CREATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'

export const FETCH_TODO = 'FETCH_TODO'
export const FETCH_TODO_SUCCESS = 'FETCH_TODO_SUCCESS'
export const FETCH_TODO_ERROR = 'FETCH_TODO_ERROR'

export const DELETE_CLOUD_TODO = 'DELETE_CLOUD_TODO'
export const UPDATE_CLOUD_TODO = 'UPDATE_CLOUD_TODO'
