export const CREATE_TODO = 'CREATE_TODO'
export const DELETE_TODO = 'DELETE_TODO'
export const UPDATE_TODO = 'UPDATE_TODO'

export const FETCH_CONTACT = 'FETCH_CONTACT'
export const CONTACT_SUCCESS = 'CONTACT_SUCCESS'
export const CONTACT_ERROR = 'CONTACT_ERROR'
